version: "3.9"
services: 
  mqttsubscriber: # move sensor data from mqtt broker to node exporter
    build: .
    command: python -m sub
    volumes: 
      - ./exporter:/exporter # need to write *.prom so node exporter textfile collector can pick up metrics    
  mqttbroker:
    image: hivemq/hivemq4
    restart: always    
    ports:
      - "8080:8080"
      - "1883:1883"
  prometheus: 
    image: prom/prometheus 
    restart: always    
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/prometheus/data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'      
  nodeexporter:
    image: prom/node-exporter
    restart: always    
    volumes: 
      - ./exporter:/exporter
    command: 
      - '--collector.textfile.directory=/exporter'
    ports:
      - "9100:9100"      
  grafana:
    image: grafana/grafana-oss
    restart: always
    volumes: 
      - ./grafana:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false      
    ports:
      - "3000:3000"

# https://github.com/stefanprodan/dockprom